# The ip and port to listen on.
# 0.0.0.0 to listen on any IP
listen = "0.0.0.0:9092"

# Specify which hostname to return to the clients. Leave absent to use the result of hostname() call
# hostname = "someserver"

# How often the cleaner thread wakes up (ms)
cleanup = 10000

# Each topic may have those fields:
# - name (mandatory)
# - compacted (true/false, defatult false)
# - retention (ms, the records old than this will be deleted)

topics = [
  {name = "test"},
  {name = "test01"},
  {name = "test02", compacted = true },
  {name = "test03", retention = 10000} 
]

[database]
url = "postgres://avorona:avorona@localhost"


# Alternative syntax for topics
# [[topics]]
# name= "test01"
# 
# [[topics]]
# name= "test02"
# compacted = true
#
# [[topics]]
# name= "test03"
# retention = 10000
